"""Initial migration

Revision ID: a346704f3980
Revises: 
Create Date: 2024-10-26 20:30:42.934084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a346704f3980'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=321),
               type_=sa.String(length=150),
               nullable=True)
        batch_op.drop_column('full_name')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False))
        batch_op.add_column(sa.Column('full_name', mysql.LONGTEXT(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=321),
               nullable=False)
        batch_op.drop_column('name')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
